import pg from 'pg'

export class PostgresAdapter {
  constructor(connectionString) {
    this.pool = new pg.Pool({ connectionString })
  }

  async query(text, params = []) {
    return this.pool.query(text, params)
  }

  async execute(text, params = []) {
    const result = await this.pool.query(text, params)
    return { rowCount: result.rowCount }
  }

  async migrate(schemaSql) {
    const statements = schemaSql
      .split(';')
      .map(s => s.trim())
      .filter(s => s.length > 0)

    for (const stmt of statements) {
      const pgSql = this._toPostgres(stmt)
      try {
        await this.pool.query(pgSql)
      } catch (err) {
        if (!err.message.includes('already exists')) throw err
      }
    }
  }

  async close() {
    await this.pool.end()
  }

  _toPostgres(sqliteSql) {
    let sql = sqliteSql
      .replace(/AUTOINCREMENT/g, 'GENERATED BY DEFAULT AS IDENTITY')
      .replace(/`/g, '"')
      .replace(/CHECK\s*\([^)]*\)/g, '')
      .replace(/FOREIGN KEY\s*\([^)]+\)\s*REFERENCES\s*\w+\s*\([^)]+\)\s*(ON DELETE (CASCADE|SET NULL|SET DEFAULT|RESTRICT))?\s*,?/g, '')
    if (sql.includes('INSERT INTO plans')) return ''
    if (sql.includes('CREATE TABLE IF NOT EXISTS')) {
      sql = sql.replace('CREATE TABLE IF NOT EXISTS', 'CREATE TABLE IF NOT EXISTS')
    }
    sql = sql.replace(/"([^"]+)"\./g, '$1.')
    sql = sql.replace(/CHECK\s*\([^)]*\)/g, '')
    return sql.trim()
  }
}
